### ISSUE TITLE
Can I config the number of choices?

### ISSUE THREAD

**Issue by Sixpsy** [LakeYS/Discord-Trivia-Bot#148]
I'm running bot from my PC but when I use 3 choices question the bot cant run. Please guide me how to config this. Thank you.

**Comment by LakeYS** [comment]
Questions are currently formatted exactly like OpenTDB questions, meaning that they must either be true/false, or multiple choice with one answer and three incorrect answers. This may change in the future, but for now it is by design so questions are consistent. Your best bet would be to come up with a fourth answer and add it to the question(s).
