### ISSUE TITLE
please update config description on lakeys.net

### ISSUE THREAD

**Issue by jannyba** [LakeYS/Discord-Trivia-Bot#201]
Hi

please update configuration description on lakeys.net, for example there is missing use-fixed-rounds, rounds-fixed-number, reveal-answers, additonal-packages, additional-packages-root, debug-log, debug-database-flush etc.

**Comment by LakeYS** [comment]
Hi. Regarding `use-fixed-rounds` and `rounds-fixed-number`, these two config options are currently only on the live branch--the latest release of TriviaBot does not yet include them. They will be added to the install page once they reach a stable release.

`debug-log` is strictly for development. `additional-packages`, `additional-packages-root`, and `debug-database-flush` are deprecated functions.

The config descriptions on the install page are intended to be short and simple, rather than definitive, hence why the above options are omitted. Further documentation is planned in a future release, but this is intentional for the time being.

**Comment by jannyba** [comment]
I see, so if I'm using
`git -C /home/Dragy/Discord-Trivia-Bot/ pull origin master -v `
for updating, that is not the desired way?
