### ISSUE TITLE
Answers containing diacritics are not sorted consistently

### ISSUE THREAD

**Issue by jannyba** [LakeYS/Discord-Trivia-Bot#214]
Hi

I just found out, when question is showed it has the same ABCD answers everytime, can they be randomized?

Sometimes the correct answer is the same letter for like 10 questions in a row, can this be a bug?

In both cases local question database is used.

thx

**Comment by LakeYS** [comment]
Answers are currently sorted in reverse alphabetical order as seen [here](https://github.com/LakeYS/Discord-Trivia-Bot/blob/master/triviabot.js#L1029)--this is intentional. In the instance of having the same letter, can you verify if the answers are sorting? It may be related to how they are formatted in some form as well.

**Comment by jannyba** [comment]
When answers start with a same letter it's ok, they are sorted by next letters.
Not sure if that is important actually, or why they need to be sorted alphabetically, but sorting script doesn't recognize correctly letters with diacritics, so:
correct way: a á b c č d ď e é
trivia bot is sorting like: a b c d e .. x y z á č ď é...

**Comment by LakeYS** [comment]
I see! Will take a look at this
